/**
 * Regenerates the census artifacts from the ledger, or checks them for drift.
 *
 * `--check` is the mode that matters. The census artifacts drifted once, in the
 * direction that flattered nothing in particular -- three overturned negatives
 * sat in the summary because the summary was maintained by hand and a pull
 * request's prose had become the source of truth. Nobody noticed for days,
 * because a stale number looks exactly like a fresh one.
 *
 * So the artifacts are derived and CI recomputes them. If the file on disk is
 * not what the ledger implies, the build fails and says which candidate moved.
 *
 * Usage:
 *   node --experimental-strip-types bench/cdeb/freeze/census-generate-v5.ts --study-root <dir> [--check]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { canonicalAdjudication } from "./adjudicate-v5.ts";
import {
  censusRowsFrom,
  reduceLedger,
  summarize,
  type CensusRow,
  type LedgerRow,
} from "./census-ledger-v5.ts";

interface Population {
  readonly candidate_id: string;
  readonly repository_id: string;
}

const readJsonl = <T>(path: string): T[] =>
  readFileSync(path, "utf8")
    .split("\n")
    .filter((line) => line.trim() !== "")
    .map((line) => JSON.parse(line) as T);

const stableJsonl = (rows: readonly CensusRow[]): string =>
  rows.map((row) => JSON.stringify(row)).join("\n") + "\n";

/**
 * The human-readable report.
 *
 * Deliberately reports the negative under its full name every time it appears.
 * The short name is what travels, and the short name is the one that made a
 * bounded search sound like a property of the tree.
 */
const renderReport = (
  summary: ReturnType<typeof summarize>,
  rows: readonly CensusRow[],
  generatedFrom: string,
): string => {
  const repositories = [...new Set(rows.map((row) => row.repository_id))].sort();
  const lines = [
    "<!-- generated by bench/cdeb/freeze/census-generate-v5.ts; edit the ledger, not this file -->",
    "",
    "# CDEB-Fresh v5 — Stage 1-r1 buildability census",
    "",
    `Derived from \`${generatedFrom}\`. Every number below is recomputed from the`,
    "append-only adjudication ledger; nothing here is maintained by hand.",
    "",
    `- candidates: **${String(summary.total)}**`,
    `- decided: **${String(summary.decided)}**`,
    `- undecided: **${String(summary.undecided)}**`,
    `- candidates whose current verdict replaced a different earlier one: **${String(summary.overturned)}**`,
    "",
    "## By disposition",
    "",
    "| disposition | candidates |",
    "| --- | ---: |",
    ...Object.entries(summary.by_disposition)
      .sort(([, left], [, right]) => right - left)
      .map(([key, count]) => `| \`${key}\` | ${String(count)} |`),
    "",
    "## By repository",
    "",
    ...repositories.flatMap((repository) => {
      const counts = summary.by_repository[repository] ?? {};
      return [
        `### ${repository}`,
        "",
        ...Object.entries(counts)
          .sort(([, left], [, right]) => right - left)
          .map(([key, count]) => `- \`${key}\`: ${String(count)}`),
        "",
      ];
    }),
    "## How to read the negative",
    "",
    "`NO_PASSING_REVIVAL_FOUND_WITHIN_SEARCH_BUDGET` is a statement about this",
    "search, not about the tree. Each one required at least three structurally",
    "distinct revival shapes to fail before it was recorded, and a shape nobody",
    "tried is not a shape that does not exist. An earlier revision of this study",
    "called the same outcome TREE_ENFORCED, which reads as a demonstrated",
    "property; it was not one, and the rename is the correction.",
    "",
    "`VOID_INVALID_ACCEPTANCE` rows are adjudications whose acceptance run could",
    "not be verified. They are preserved and never reused, and the candidates",
    "they touched are counted as undecided rather than as negatives.",
    "",
  ];
  return lines.join("\n");
};

const main = (): number => {
  const argv = process.argv.slice(2);
  const rootIndex = argv.indexOf("--study-root");
  if (rootIndex === -1 || argv[rootIndex + 1] === undefined) {
    console.error("census-generate: --study-root <dir> is required");
    return 2;
  }
  const stage = join(argv[rootIndex + 1] as string, "stage1-r1");
  const check = argv.includes("--check");

  const ledgerPath = join(stage, "g4-adjudication.jsonl");
  const censusPath = join(stage, "buildability-census.jsonl");
  const summaryPath = join(stage, "buildability-summary.json");
  const reportPath = join(stage, "CENSUS-REPORT.md");

  const ledger = readJsonl<LedgerRow>(ledgerPath);
  for (const row of ledger) canonicalAdjudication(row.adjudication);

  // The population is the census file's candidate set: it is the frozen corpus
  // and does not change with adjudication. Reading it from the ledger instead
  // would let a candidate nobody adjudicated disappear from the denominator.
  const population: Population[] = readJsonl<Population>(censusPath).map((row) => ({
    candidate_id: row.candidate_id,
    repository_id: row.repository_id,
  }));

  const reduced = reduceLedger(ledger, population);
  const rows = censusRowsFrom(reduced);
  const summary = summarize(reduced);

  const wanted: Array<readonly [string, string]> = [
    [censusPath, stableJsonl(rows)],
    [summaryPath, JSON.stringify({ schema_version: 2, generated_from: ledgerPath, summary }, null, 2) + "\n"],
    [reportPath, renderReport(summary, rows, ledgerPath)],
  ];

  if (!check) {
    for (const [path, content] of wanted) writeFileSync(path, content);
    console.log(`census-generate: wrote ${String(wanted.length)} artifact(s) from ${String(ledger.length)} ledger row(s)`);
    return 0;
  }

  const drifted: string[] = [];
  for (const [path, content] of wanted) {
    let actual = "";
    try {
      actual = readFileSync(path, "utf8");
    } catch {
      drifted.push(`${path} is missing`);
      continue;
    }
    if (actual !== content) drifted.push(path);
  }
  if (drifted.length > 0) {
    console.error(
      `census-generate: ${String(drifted.length)} artifact(s) do not match the ledger: ${drifted.join(", ")}. ` +
        `Regenerate with npm run bench:cdeb:v5:census -- the ledger is the source of truth and these files are not ` +
        `edited by hand`,
    );
    return 1;
  }
  console.log(`census-generate: artifacts match the ledger (${String(ledger.length)} row(s))`);
  return 0;
};

process.exit(main());
